[package]
name = "smv"
version = "0.1.0"
authors = ["Joseph Kato <joseph@jdkato.io>"]

[dependencies]
syntect = "1.8"
serde_json = "1.0"
serde_derive = "1.0.15"
serde = "1.0.15"
clap = "2"
libc = "0.2"
